# Generated by Django 4.2.6 on 2024-11-30 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
            ],
            options={
                'db_table': 'carts',
            },
        ),
        migrations.CreateModel(
            name='CartProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_id', models.IntegerField()),
                ('lines', models.JSONField()),
                ('district', models.JSONField()),
                ('cost', models.IntegerField()),
            ],
            options={
                'db_table': 'cart_products',
            },
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('value', models.JSONField()),
                ('user_id', models.IntegerField()),
            ],
            options={
                'db_table': 'datas',
            },
        ),
        migrations.CreateModel(
            name='SubwayEdge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_id', models.IntegerField()),
                ('end_id', models.IntegerField()),
                ('cost', models.FloatField(blank=True, null=True)),
                ('line', models.CharField(max_length=20)),
                ('type', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'subway_edges',
            },
        ),
        migrations.CreateModel(
            name='SubwayStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('line', models.CharField(max_length=20)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('district', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'subway_stations',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('login_id', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('cash', models.IntegerField()),
            ],
            options={
                'db_table': 'custom_users',
            },
        ),
    ]
